version: '3.7'

services:
  db:
    image: postgres
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    networks:
      - backend
      
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - .:/code
    env_file:
      - ".env"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge